config/routes.rb
Rails.application.routes.draw do

  get 'movies_list/list'

  get 'movies/addmovies'
  get 'welcome/index'
root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def addmovies
  end
end

app/controllers/movies_list_controller.rb
class MoviesListController < ApplicationController
  def list
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/add_helper.rb
module AddHelper
end

app/helpers/addmoives_helper.rb
module AddmoivesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/movies_list_helper.rb
module MoviesListHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCinema</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/addmovies.html.erb
<div style="margin-left:10px">
<h1>add movies</h1>
<p>If you want to add a movie, use this form. If a movie passes the tests but only on a technicality (like a woman only speaking to a minor character once) you can mention this in the <b>Comments</b> field. Feel free to enter other comments there as well (if you want to name all moments in the movie that cause it to pass, for example, feel free to do so).</p>
<form method="post" >
    <fieldset>
        <legend>The movie</legend>
        <p><label for="imdb">IMDb link</label><input class="" id="imdb" type="text" name="imdb"> <input type="button" name="fetchinfo" onclick="fetchInfo();" value="Get title and year"><span style="display: none;" id="progressIndicator"> <img src="/static/progress.gif" alt="[Busy...]" title="Fetching movie info from IMDb..."></span></p>
        <p><label for="title">Title</label>
        <input type="text" name="title" id="title" class=""></p>
        <p><label for="year">Year</label>
        <input type="text" name="year" size="6" id="year" class=""></p>
    </fieldset>

    <fieldset>
        <legend>The rating</legend>  <p><input type="radio" name="rating" id="test0" value="0"><label for="test0">This movie doesn't have two (named) female characters.</label></p>
        <p><input type="radio" name="rating" id="test1" value="1"><label for="test1">It has at least two women in it;</label></p>
        <p><input type="radio" name="rating" id="test2" value="2"><label for="test2">... and they talk to each other;</label></p>
        <p><input type="radio" name="rating" id="test3" value="3"><label for="test3">... about something besides a man.</label></p>
        <p style="padding-top: 5px;"><input type="checkbox" name="dubious" id="dubious"><label for="dubious">Although I think it matches, it's dubious.</label></p>
    </fieldset>

    <fieldset>
        <legend>Your comment</legend>
        <p>Please give some information on why this movie got this rating. In particular when a movie matches all tests, it's helpful to describe why it matches (for example, just because two women speak for half a minute in one scene, or because there are actual important female characters that discuss plot-relevant things regularly).</p>
        <textarea rows="8" cols="40" name="comment" class=""></textarea>
    </fieldset>

    <fieldset>
        <legend>Your contact info</legend>
        <p><label for="yourname">Name or handle</label>
           <input type="text" name="name" id="yourname" class=""></p>

        <p><label for="youremail">E-mail address</label>
           <input type="email" name="email" id="youremail" class=""> (won't be visible)</p>

    </fieldset>
   <div class="submit"><input type="submit" value="Submit"></div>
   <%= link_to 'movieslist' , movies_list_list_path %>
    <div style="display: none;"><input type="hidden" name="add" value="yup"></div>
   <p style="font-size: 80%;">By adding a movie to the list you agree that it will be available with all other movies and ratings licensed as <a href="http://creativecommons.org/licenses/by-nc/3.0/"><img src="/static/by-nc-30-80x15.png" alt="Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)" title="Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)"></a></p>

</form>	
</div>

app/views/movies_list/list.html.erb
<h1>List movies</h1>
<%= link_to 'back' ,  welcome_index_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bechdel Test For Tamil Cinema</title>

  
   <%= stylesheet_link_tag "bechdel" %>
</head>


<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i> SWIFT                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Get Involved</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1>Bechdel Test For Tamil Cinema</h1 >
                        <p class="intro-text">To gauge the nature of women's presence in Tamil movies.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Bechdel Test</h2>
                <p>The Bechdel Test is a simple way to gauge the nature of women's presence in movies (and other works of fiction). For a movie to pass this test, the criteria is as follows:<br>

1. The movie must have atleast two women (with names) <br>
2. Who talk to each other <br>
3. About anything but a man.</p>
                <p>The test has been run on English movies for many years now and there is ample data (even APIs) and research material available. However, there is no such data available for Tamil Cinema. This project will serve as a platform for a crowd sourcing the data and results of the Bechdel test for Tamil movie. We hope to make the platform language agnostic in the future.</p>
              
               <%= link_to 'add' , movies_addmovies_path %>
               <%= link_to 'movieslist' , movies_list_list_path %>

            </div>
        </div>
    </section>
    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Bechdel Test</h2>
                    <p>If you wish to make the project better by contributing to code, here's the link to the Gitlab repo.</p>
                    <a href="https://gitlab.com/fsftn/Bechdel-test-for-tamil-cinema" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Bechdel Test</h2>
                <p>Feel free to email us to provide some feedback on our Project, give us suggestions for new ideas, to our swift mailnglist.</p>
                <p><a href="mailto:feedback@startbootstrap.com">swift@fsftn.org</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://gitlab.com/fsftn/Bechdel-test-for-tamil-cinema" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Gitlab</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

       
    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2016</p>
        </div>
    </footer>

  

</body>

</html>